web_information_gathering_task:
  description: >
    Using the research plan, search the general web for information relevant to the specified sub-questions.
    Focus on finding diverse perspectives, blogs, forums, news articles, and potentially primary sources
    available online. Summarize key findings and provide URLs for each relevant source.
    Use time period: {today}.
    Use the same language and country as the topic: "{topic}".
  expected_output: >
    A detailed result for each relevant source, including: URL, comprehensive summary (covering key points, arguments, or data), 
    relevant quotes or data points extracted,
    and an explanation of how the source contributes to answering the sub-questions, 
    organized by sub-question if possible.
  agent: web_search_specialist

source_evaluation_task:
  description: >
    Review the compiled lists of sources from the search tasks. For each source, assess its relevance,
    credibility, potential biases, timeliness, and overall quality. Create a filtered and annotated
    list of high-quality, relevant sources to be used for synthesis. Discard low-quality or irrelevant findings.
  expected_output: >
    A consolidated, annotated list of evaluated sources, including source details, evaluation notes 
    (Credibility score, Bias assessment, Relevance justification, Timeliness note), and a clear indication
    of which sources are recommended for synthesis.
  agent: source_evaluator

synthesize_findings_task:
  description: >
    Based only on the evaluated and recommended sources, read and analyze the information. Identify the main
    themes, key arguments, supporting evidence, counter-arguments, data points, expert opinions, areas of consensus,
    areas of disagreement, and significant knowledge gaps. Structure these findings logically.
  expected_output: >
    A structured document containing synthesized key findings organized logically, identification of patterns,
    trends, contradictions, summary of evidence supporting each point (with references to specific sources),
    and highlighting of knowledge gaps or areas needing further research.
    Use time period: {today}.
    Use the same language and country as the topic: "{topic}".
  agent: research_synthesizer

compile_report_task:
  description: >
    Using the structured synthesis and the list of evaluated sources, write a comprehensive and polished
    research report. Follow the structure defined in the research plan. Ensure clear language, logical flow,
    and accurate citations for all claims, referencing the evaluated sources.        
  expected_output: >
    The final, well-formatted research report addressing the initial topic comprehensively, based on evaluated evidence.
      Include Title, Executive Summary, Introduction/Background/Scope, Detailed Findings (with citations),
      Conclusion/Summary of Key Insights/Knowledge Gaps, and Bibliography.
      Use tables extensively to represent comparative data, highlight key points, and summarize findings wherever applicable.        
      Use time period: {today}.

      Use the same language and country as the topic: "{topic}".
  agent: report_writer
